### ISSUE TITLE
Error when running npm run hot

### ISSUE THREAD

**Issue by boka18** [huwcarwyn/react-laravel-boilerplate#20] opened 2019-06-25 10:53 UTC
When I run `npm run hot` everything looks normal in terminal, but whenever I change something the view doesn't reload. It doesn't even display the change after a manual refresh.

This is what I get in my browsers console:
```
React-Hot-Loader: misconfiguration detected, using production version in non-production environment.
```
But I can see that in `npm run hot` there is explicitly said to use the DEV environment. Any help is appreciated :)

*Update*:
When i run `npm run dev` it will display the latest changes after a manual refresh, but the error message in the console is still there.

**Comment by huwcarwyn** [comment] 2019-06-26 08:50
I'll have a look tonight on this one

**Comment by huwcarwyn** [comment] 2019-06-29 20:00
Very strange, could you pull my latest updates and see if the issue persists? Can you check that you have set your environment variables correctly too? I was not able to reproduce this one.

**Comment by huwcarwyn** [comment] 2019-07-02 15:23
I have not been able to replicate - closing this. Feel free to comment and I'll re-open.

**Closed by huwcarwyn** 2019-07-02 15:23 UTC
